name: Deploy Vite PWA React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 22.5.1
        uses: actions/setup-node@v3
        with:
          node-version: '22.5.1'  # Aquí puedes mantener la versión de Node.js que estás utilizando
          cache: 'pnpm'

       # Step 3: Install PNPM
      - name: Install PNPM
        run: npm install -g pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

    # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3